# Generated by Django 3.2.23 on 2023-11-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('type', models.CharField(default='layers', max_length=70)),
            ],
        ),
    ]
