# Generated by Django 3.2.23 on 2023-11-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0002_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ImageField(upload_to='productprices')),
                ('title', models.CharField(max_length=70)),
                ('price', models.CharField(max_length=70)),
            ],
        ),
    ]
