# Generated by Django 3.2.23 on 2023-11-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0003_productpricemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=70)),
                ('price', models.CharField(max_length=70)),
            ],
        ),
        migrations.DeleteModel(
            name='ProductPriceModel',
        ),
    ]
