# Generated by Django 3.2.23 on 2023-11-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0004_auto_20231122_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70)),
                ('phone', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('product', models.CharField(max_length=70)),
                ('message', models.TextField()),
            ],
        ),
    ]
