# Generated by Django 3.2.23 on 2023-11-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0006_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSingle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70)),
                ('website', models.CharField(max_length=70)),
                ('comment', models.TextField()),
            ],
        ),
    ]
