# Generated by Django 3.2.23 on 2023-11-23 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0008_subscriber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogSingle',
            new_name='Blog_single',
        ),
    ]
